CREATE OR REPLACE VIEW `gen-lang-client-0738410622.marketing_data.v_fb_ads_duoc` AS
SELECT 
  inserted_at,
  run_date,
  start_date,
  end_date,
  account_id,
  ad_id,
  ad_name,
  campaign_name,
  specialty_code,
  specialty_name,
  doctor_name,
  post_id,
  post_link,
  thumbnail_url,
  content,
  status,
  effective_status,
  is_active,
  spend,
  mes,
  cmt,
  clicks,
  impressions,
  reach,
  video_views,
  video_25,
  video_50,
  video_75,
  video_95,
  video_100,
  thruplay,
  report_type,
  page_name
FROM `gen-lang-client-0738410622.marketing_data.fb_ad_insights`
WHERE specialty_code IN ('VT', 'BA');
